export const ANIME_LIST_REQUEST = "ANIME_LIST_REQUEST";
export const ANIME_LIST_RECEIVED = "ANIME_LIST_RECEIVED";
export const ANIME_LIST_ERROR = "ANIME_LIST_ERROR";
export const ANIME_LIST_ADD = "ANIME_LIST_ADD";

export const ANIME_REQUEST = "ANIME_REQUEST";
export const ANIME_RECEIVED = "ANIME_RECEIVED";
export const ANIME_ERROR = "ANIME_ERROR";
export const ANIME_UNLOAD = "ANIME_UNLOAD";

export const EPISODE_LIST_REQUEST = "EPISODE_LIST_REQUEST";
export const EPISODE_LIST_RECEIVED = "EPISODE_LIST_RECEIVED";
export const EPISODE_LIST_ERROR = "EPISODE_LIST_ERROR";
export const EPISODE_LIST_UNLOAD = "EPISODE_LIST_UNLOAD";
