export const ANIME_LIST_REQUEST = "ANIME_LIST_REQUEST";
export const ANIME_LIST_RECEIVED = "ANIME_LIST_RECEIVED";
export const ANIME_LIST_ERROR = "ANIME_LIST_ERROR";

export const ANIME_REQUEST = "ANIME_REQUEST";
export const ANIME_RECEIVED = "ANIME_RECEIVED";
export const ANIME_ERROR = "ANIME_ERROR";
export const ANIME_UNLOAD = "ANIME_UNLOAD";
export const ANIME_REMOVED = "ANIME_REMOVED";
export const ANIME_ADDED = "ANIME_ADDED";

export const EPISODE_LIST_REQUEST = "EPISODE_LIST_REQUEST";
export const EPISODE_LIST_RECEIVED = "EPISODE_LIST_RECEIVED";
export const EPISODE_LIST_ERROR = "EPISODE_LIST_ERROR";
export const EPISODE_LIST_UNLOAD = "EPISODE_LIST_UNLOAD";

export const EPISODE_ADDED = "EPISODE_ADDED";
export const EPISODE_REMOVED = "EPISODE_REMOVED";

export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";
export const USER_SET_ID = "USER_SET_ID";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_RECEIVED = "USER_PROFILE_RECEIVED";
export const USER_PROFILE_ERROR = "USER_PROFILE_ERROR";

export const alertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR"
};
